jobs:
  build:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/Online-Store
    steps:
      - checkout
      - run: npm install
      - run: npm build
      - store_artifacts:
          path: dist

  deploy:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/Online-Store
    steps:
      - checkout
      - run: npm install
      - run: npm deploy
      - store_artifacts:
          path: deploy-logs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
