version: 2.1

orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.0.0
  
jobs:
  build:
    docker:
      - image: circleci/node:7.10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm test
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          token: CODECOV_TOKEN 
          validate_url: true 
          flags: unittests , integration 
          url: https://app.codecov.io/gh/Thembanator1/Online-Store/new 

workflows:
  example-workflow:
    jobs:
      - example-job
  
  

