version: 2.1
orbs:
  codecov: codecov/codecov@3
orbs:
  codecov: codecov/codecov@1.1.0
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - codecov/upload:
          file: coverage.xml
          token: d6bf52c7-73cf-4796-847c-75e56793f9ba


jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm run test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
